=== razagilani/billing/SkylineBill.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Rich Andrews (self) -->
<xs:schema xmlns:sb="SkylineBill" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="SkylineBill" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="skylinebill">
		<xs:annotation>
			<xs:documentation>Given a SNUB and rate schedule, all the consumption data necessary to compute SNOB</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="measuredusage" maxOccurs="2">
					<xs:annotation>
						<xs:documentation>Usage per service</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meter" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="identifier"/>
										<xs:element name="register" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="identifier"/>
													<xs:element name="units"/>
													<xs:element name="description"/>
													<xs:element name="total"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="service">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="gas"/>
									<xs:enumeration value="electric"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== razagilani/billing/sample/Skyline-PECO-9443-01819-2009100609.xml
<?xml version="1.0" encoding="UTF-8"?>
<sb:skylinebill xmlns:sb="skylinebill" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="skylinebill ..\SkylineBill.xsd">
	<sb:measuredusage service="gas">
		<sb:meter>
			<sb:identifier>027870434</sb:identifier>
			<sb:register>
				<sb:identifier>027870434</sb:identifier>
				<sb:description>Total CCF</sb:description>
				<sb:units>CCF</sb:units>
				<sb:total>151</sb:total>
			</sb:register>
		</sb:meter>
		<sb:meter>
			<sb:identifier>028702956</sb:identifier>
			<sb:register>
				<sb:identifier>028702956</sb:identifier>
				<sb:description>Total CCF</sb:description>
				<sb:units>CCF</sb:units>
				<sb:total>97</sb:total>
			</sb:register>
		</sb:meter>
	</sb:measuredusage>
	<sb:measuredusage service="electric">
		<sb:meter>
			<sb:identifier>084010385</sb:identifier>
			<sb:register>
				<sb:identifier>084010385</sb:identifier>
				<sb:description>Total kWh</sb:description>
				<sb:units>kWh</sb:units>
				<sb:total>1200</sb:total>
			</sb:register>
		</sb:meter>
	</sb:measuredusage>
</sb:skylinebill>
