=== razagilani/billing/UtilityBill.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Rich Andrews (Skyline Innovations) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="utilitybill">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="car">
					<xs:annotation>
						<xs:documentation>Customer Account Record.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="accountnumber" type="xs:string">
								<xs:annotation>
									<xs:documentation>Customer account number used by the utility</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="serviceaddress" type="address">
								<xs:annotation>
									<xs:documentation>Location where utility service is received.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="billingaddress" type="address">
								<xs:annotation>
									<xs:documentation>Location where bills are sent</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="uar">
					<xs:annotation>
						<xs:documentation>Utility Account Record - contact information for the utility.  Payee of this bill.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tin">
								<xs:annotation>
									<xs:documentation>Utility tax payer identification number</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="customerservice" type="address" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Utility contact information including accessibility numbers, Spanish speaking representatives and other customer oriented care.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="paymentlocation" type="address" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Physical locations where payment can be made or sent.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="suppliercontact" type="address" minOccurs="0"/>
							<xs:element name="emergencycontact" type="address" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Contact information for emergency related to service location.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="utilitycommission" type="address" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Regulatory commission.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="writteninquiries" type="address" minOccurs="0"/>
							<xs:element name="missutility" type="address" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Utility/contractor coordinate number.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="serviceoutage" type="address" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="unknownaddress" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Address records not accounted for yet present in bill.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="address">
								<xs:attribute name="description" use="required"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="summary">
					<xs:annotation>
						<xs:documentation>Bill summary.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="priorbalance" type="xs:decimal">
								<xs:annotation>
									<xs:documentation>Balance from last bill.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="previouspayment" type="payment" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Previous payments after last bill</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="adjustment" type="payment" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Charges and credit for late fees as well as unknown reasons.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="balanceforward" type="xs:decimal" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Balance forward for this bill</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="billperiodbegin" type="xs:date">
								<xs:annotation>
									<xs:documentation>Begin date for this bill.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="billperiodend" type="xs:date">
								<xs:annotation>
									<xs:documentation>End date for this bill.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="issuedate" type="xs:date">
								<xs:annotation>
									<xs:documentation>Date the bill is issued for customer.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="currentcharges" maxOccurs="2">
								<xs:annotation>
									<xs:documentation>Total for this bill period including distribution and service lates fees, taxes and various other charges.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:decimal">
											<xs:attributeGroup ref="service"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="totaldue" type="xs:decimal">
								<xs:annotation>
									<xs:documentation>Total account balance (consider renaming it to) for entire bill including all payees, previous balance, late fees.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="duedate" type="xs:date">
								<xs:annotation>
									<xs:documentation>Date bill is due payable.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="latepayment">
								<xs:annotation>
									<xs:documentation>Penalty if bill not paid by due date.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="penalty">
											<xs:annotation>
												<xs:documentation>Percentage charge of total bill for missed due date</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="amount">
											<xs:annotation>
												<xs:documentation>Amount of late payment fee</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="details" maxOccurs="2">
					<xs:annotation>
						<xs:documentation>Details necessary for bill computation.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rateschedule">
								<xs:annotation>
									<xs:documentation>Name of rate.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name"/>
										<xs:element name="rateineffect" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="chargegroup" maxOccurs="4">
								<xs:annotation>
									<xs:documentation>Group of charges by generation/supply, transmission, distribution or taxation</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="charges">
											<xs:annotation>
												<xs:documentation>Detail charges for distribution.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="charge" type="charge" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="subtotal" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:fractionDigits value="2"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Generation/Supply"/>
												<xs:enumeration value="Transmission"/>
												<xs:enumeration value="Distribution"/>
												<xs:enumeration value="Tax"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="total" type="xs:decimal"/>
						</xs:sequence>
						<xs:attributeGroup ref="service"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="billableusage" maxOccurs="2">
					<xs:annotation>
						<xs:documentation>Billable usage which may differ from measured usage</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rateschedule">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name"/>
										<xs:element name="rateineffect" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="usage" type="usage" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="total" minOccurs="0">
								<xs:annotation>
									<xs:documentation>total billable</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="service"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="measuredusage" maxOccurs="2">
					<xs:annotation>
						<xs:documentation>Meters associated with service location.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meter" maxOccurs="unbounded">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="meter"/>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="nextreaddate" type="xs:date" minOccurs="0">
								<xs:annotation>
									<xs:documentation>For premises wide next read date.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="service"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="usagehistory" minOccurs="0" maxOccurs="2">
					<xs:annotation>
						<xs:documentation>Summary of prior usage by period.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="usage" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date">
											<xs:annotation>
												<xs:documentation>usage period date, usually in the form of YYYY-MM use DD 01 if missing.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="days" type="xs:integer" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Number of days in period.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="register">
											<xs:annotation>
												<xs:documentation>Net and submeter registers. May be identified by id or type/bucket.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="identifier"/>
													<xs:element name="total">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:integer">
																	<xs:attribute name="units"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="total">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:integer">
														<xs:attribute name="units"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="service"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:annotation>
					<xs:documentation>The unique SI identifier for this bill</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="address">
		<xs:sequence>
			<xs:element name="addressee"/>
			<xs:element name="street"/>
			<xs:element name="city"/>
			<xs:element name="state"/>
			<xs:element name="country"/>
			<xs:element name="postalcode"/>
			<xs:element name="telephonenumber"/>
			<xs:element name="hours"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="meter">
		<xs:sequence>
			<xs:element name="estimated" type="xs:boolean"/>
			<xs:element name="priorreaddate" type="xs:date" minOccurs="0"/>
			<xs:element name="presentreaddate" type="xs:date" minOccurs="0"/>
			<xs:element name="nextreaddate" type="xs:date" minOccurs="0"/>
			<xs:element name="identifier">
				<xs:annotation>
					<xs:documentation>Identifier for the physical meter</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="register" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Registers.  May be identified by id or type/bucket. (e.g. kWh)</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="identifier">
							<xs:annotation>
								<xs:documentation>Identifier for register.  Use meter identifier if unavailable.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="description"/>
						<xs:element name="units" type="xs:string" minOccurs="0"/>
						<xs:element name="priorreading" type="xs:decimal" minOccurs="0"/>
						<xs:element name="presentreading" type="xs:decimal" minOccurs="0"/>
						<xs:element name="factor" type="xs:integer" minOccurs="0"/>
						<xs:element name="total" type="xs:decimal"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="amount"/>
	<xs:complexType name="supplier"/>
	<xs:complexType name="payment">
		<xs:sequence>
			<xs:element name="payee"/>
			<xs:element name="amount" type="xs:decimal"/>
			<xs:element name="date" type="xs:date" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="charge">
		<xs:all>
			<xs:element name="snubchargeid" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Reference to normalized charge item</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="description"/>
			<xs:element name="quantity" minOccurs="0">
				<xs:complexType mixed="true">
					<xs:attribute name="units"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="rate" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="units"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="total" nillable="false">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="usage">
		<xs:all>
			<xs:element name="description"/>
			<xs:element name="quantity">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="units">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="kWh"/>
										<xs:enumeration value="CCF"/>
										<xs:enumeration value="kW"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:attributeGroup name="service">
		<xs:attribute name="service" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="gas"/>
					<xs:enumeration value="electric"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
</xs:schema>

=== razagilani/billing/doc/sample/Pepco-3091-4490-03-20080908.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Rich Andrews (self) -->
<ub:utilitybill id="112937812397813" xsi:schemaLocation="utilitybill ../UtilityBill.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ub="utilitybill">
	<ub:car>
		<ub:accountnumber>3091 4490 03</ub:accountnumber>
		<ub:serviceaddress>
			<ub:addressee>College Park Carwash Inc.</ub:addressee>
			<ub:street>8616 Baltimore Ave</ub:street>
			<ub:city/>
			<ub:state/>
			<ub:country/>
			<ub:postalcode/>
			<ub:telephonenumber/>
			<ub:hours/>
		</ub:serviceaddress>
		<ub:billingaddress>
			<ub:addressee>College Park Carwash</ub:addressee>
			<ub:street>7106 Ridgewood Ave</ub:street>
			<ub:city>Chevy Chase</ub:city>
			<ub:state>MD</ub:state>
			<ub:country/>
			<ub:postalcode>20815-5148</ub:postalcode>
			<ub:telephonenumber/>
			<ub:hours/>
		</ub:billingaddress>
	</ub:car>
	<ub:uar>
		<ub:tin>53-0127880</ub:tin>
		<ub:suppliercontact>
			<ub:addressee>Washington Gas Energy Services, Inc.</ub:addressee>
			<ub:street>13865 Sunrise Valley Dr.  Suite 200</ub:street>
			<ub:city>Herndon</ub:city>
			<ub:state>VA</ub:state>
			<ub:country>USA</ub:country>
			<ub:postalcode>20171</ub:postalcode>
			<ub:telephonenumber>888-236-9437</ub:telephonenumber>
			<ub:hours/>
		</ub:suppliercontact>
	</ub:uar>
	<ub:summary>
		<ub:priorbalance>0.0</ub:priorbalance>
		<ub:previouspayment>
			<ub:payee/>
			<ub:amount>0.0</ub:amount>
		</ub:previouspayment>
		<ub:adjustment>
			<ub:payee/>
			<ub:amount>0.0</ub:amount>
		</ub:adjustment>
		<ub:balanceforward>0.0</ub:balanceforward>
		<ub:billperiodbegin>2008-02-08</ub:billperiodbegin>
		<ub:billperiodend>2008-09-03</ub:billperiodend>
		<ub:issuedate>2008-09-09</ub:issuedate>
		<ub:currentcharges service="electric">547.67</ub:currentcharges>
		<ub:currentcharges service="gas">2691.75</ub:currentcharges>
		<ub:totaldue>2691.75</ub:totaldue>
		<ub:duedate>2008-09-30</ub:duedate>
		<ub:latepayment>
			<ub:penalty/>
			<ub:amount>6.14</ub:amount>
		</ub:latepayment>
	</ub:summary>
	<ub:details service="electric">
		<ub:rateschedule>
			<ub:name>Non-Residential-MGT-LV IIB</ub:name>
			<ub:rateineffect>Summer</ub:rateineffect>
		</ub:rateschedule>
		<ub:chargegroup type="Distribution">
			<ub:charges>
				<ub:charge>
					<ub:description>Customer Charge</ub:description>
					<ub:total>36.26</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>On-Peak Energy</ub:description>
					<ub:quantity units="kWh">3520</ub:quantity>
					<ub:rate units="dollars">0.0102812</ub:rate>
					<ub:total>36.19</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Int-Peak Energy</ub:description>
					<ub:quantity units="kWh">3680</ub:quantity>
					<ub:rate units="dollars">0.0102798</ub:rate>
					<ub:total>37.83</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Off Peak Energy</ub:description>
					<ub:quantity units="kWh">8480</ub:quantity>
					<ub:rate units="dollars">0.0102806</ub:rate>
					<ub:total>87.18</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>On peak demand</ub:description>
					<ub:quantity units="kWD">54.4</ub:quantity>
					<ub:total>135.83</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Maximum demand</ub:description>
					<ub:quantity units="kWD">54.4</ub:quantity>
					<ub:total>52.13</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Franchise tax (delivery) (make tax element)</ub:description>
					<ub:quantity units="kWh">this is derived from all kWh</ub:quantity>
					<ub:rate units="dollar">0.0006200</ub:rate>
					<ub:total>9.72</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Universal service charge (make tax element)</ub:description>
					<ub:total>20.59</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>MD Environmental surcharge (make tax element)</ub:description>
					<ub:quantity units="kWh">this is derived from all kWh</ub:quantity>
					<ub:rate units="dollar">0.0001500</ub:rate>
					<ub:total>2.35</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Gross receipts tax (make tax element)</ub:description>
					<ub:quantity units="">this is derived from all charges above</ub:quantity>
					<ub:rate units="percentage">2.040800</ub:rate>
					<ub:total>8.54</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>PG County Energy (make tax element)</ub:description>
					<ub:quantity units="">this is derived from all kWh above</ub:quantity>
					<ub:rate units="dollars">0.0072860</ub:rate>
					<ub:total>114.25</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Administrative credit</ub:description>
					<ub:quantity units="">this is derived from all kWh above</ub:quantity>
					<ub:rate units="dollars">0.0013080</ub:rate>
					<ub:total>-20.50</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Generation procurement credit/charge</ub:description>
					<ub:quantity units="">this is derived from all kWh above</ub:quantity>
					<ub:rate units="dollars">0.0001843</ub:rate>
					<ub:total>2.89</ub:total>
				</ub:charge>
			</ub:charges>
			<ub:subtotal>523.26</ub:subtotal>
		</ub:chargegroup>
		<ub:chargegroup type="Generation/Supply">
			<ub:charges>
				<ub:charge>
					<ub:description>Total Use</ub:description>
					<ub:quantity units="kWh">15680</ub:quantity>
					<ub:rate units="dollars">0.129</ub:rate>
					<ub:total>2022.72</ub:total>
				</ub:charge>
				<ub:charge>
					<ub:description>Sales Tax</ub:description>
					<ub:total>121.36</ub:total>
				</ub:charge>
			</ub:charges>
			<ub:subtotal>2144.08</ub:subtotal>
		</ub:chargegroup>
		<ub:chargegroup type="Tax">
			<ub:charges>
				<ub:charge>
					<ub:description>Sales Tax</ub:description>
					<ub:quantity/>
					<ub:total>24.41</ub:total>
				</ub:charge>
			</ub:charges>
			<ub:subtotal>24.41</ub:subtotal>
		</ub:chargegroup>
		<ub:total>2691.75</ub:total>
	</ub:details>
	<ub:billableusage service="electric">
		<ub:rateschedule>
			<ub:name>Non-Residential-MGT-LV IIB</ub:name>
		</ub:rateschedule>
		<ub:total>15680</ub:total>
	</ub:billableusage>
	<ub:measuredusage service="electric">
		<ub:meter>
			<ub:estimated>true</ub:estimated>
			<ub:nextreaddate>2008-10-03</ub:nextreaddate>
			<ub:identifier/>
			<ub:register shadow="false">
				<ub:identifier>475T</ub:identifier>
				<ub:description>Kilowatt Hour Meter</ub:description>
				<ub:units>kWh</ub:units>
				<ub:priorreading>17049</ub:priorreading>
				<ub:presentreading>17247</ub:presentreading>
				<ub:factor>80</ub:factor>
				<ub:total>15840</ub:total>
			</ub:register>
			<ub:register shadow="false">
				<ub:identifier>D11</ub:identifier>
				<ub:description>Off Peak</ub:description>
				<ub:units>kWh</ub:units>
				<ub:priorreading>9276</ub:priorreading>
				<ub:presentreading>9382</ub:presentreading>
				<ub:factor>80</ub:factor>
				<ub:total>8480</ub:total>
			</ub:register>
			<ub:register shadow="false">
				<ub:identifier>D08</ub:identifier>
				<ub:description>Interm Peak</ub:description>
				<ub:units>kWh</ub:units>
				<ub:priorreading>3627</ub:priorreading>
				<ub:presentreading>3673</ub:presentreading>
				<ub:factor>80</ub:factor>
				<ub:total>3680</ub:total>
			</ub:register>
			<ub:register shadow="false">
				<ub:identifier>D05</ub:identifier>
				<ub:description>On Peak</ub:description>
				<ub:units>kWh</ub:units>
				<ub:priorreading>4145</ub:priorreading>
				<ub:presentreading>4189</ub:presentreading>
				<ub:factor>80</ub:factor>
				<ub:total>3520</ub:total>
			</ub:register>
		</ub:meter>
	</ub:measuredusage>
</ub:utilitybill>

=== razagilani/billing/sample/PECO-94443-01819-2009100609.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Rich Andrews (self) -->
<utilitybill id="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\UtilityBill.xsd">
	<car>
		<accountnumber>94443-01819</accountnumber>
		<serviceaddress>
			<addressee>T C Commons</addressee>
			<street>1103 West Chester PI, ST 12-A</street>
			<city>West Chester</city>
			<state>PA</state>
			<country>USA</country>
			<postalcode/>
			<telephonenumber>610-688-8985</telephonenumber>
			<hours/>
		</serviceaddress>
		<billingaddress>
			<addressee>T C Commons</addressee>
			<street>C/O Family Laundry Mat</street>
			<city>West Chester</city>
			<state>PA</state>
			<country>USA</country>
			<postalcode>19382-5004</postalcode>
			<telephonenumber/>
			<hours/>
		</billingaddress>
	</car>
	<uar>
		<tin/>
		<customerservice>
			<addressee>Business Account Services PECO</addressee>
			<street>2301 Market St.</street>
			<city>Philadelphia</city>
			<state>PA</state>
			<country>USA</country>
			<postalcode>19101</postalcode>
			<telephonenumber>800-980-9655</telephonenumber>
			<hours/>
		</customerservice>
		<paymentlocation>
			<addressee>PECO Energy - Payment Processing</addressee>
			<street>PO Box 37629</street>
			<city>Philadelphia</city>
			<state>PA</state>
			<country>USA</country>
			<postalcode>19101</postalcode>
			<telephonenumber/>
			<hours/>
		</paymentlocation>
		<paymentlocation>
			<addressee>PECO Energy</addressee>
			<street>2301 Market St.</street>
			<city>Philadelphia</city>
			<state>PA</state>
			<country>USA</country>
			<postalcode>19101</postalcode>
			<telephonenumber>1-877-432-9384</telephonenumber>
			<hours>M-F 8:30-5PM</hours>
		</paymentlocation>
	</uar>
	<summary>
		<priorbalance>0.0</priorbalance>
		<previouspayment>
			<payee>PECO</payee>
			<amount>2501.91</amount>
		</previouspayment>
		<billperiodbegin>2009-09-03</billperiodbegin>
		<billperiodend>2009-10-05</billperiodend>
		<issuedate>2009-10-06</issuedate>
		<currentcharges>955.91</currentcharges>
		<totaldue>2566.44</totaldue>
		<duedate>2009-10-28</duedate>
		<latepayment>
			<penalty/>
			<amount/>
		</latepayment>
	</summary>
	<currentcharges>
		<distributer>
			<priorbalance/>
			<payment/>
			<balanceforward/>
			<currentcharges/>
		</distributer>
		<supplier name="">
			<priorbalance/>
			<payment/>
			<balanceforward/>
			<currentcharges/>
		</supplier>
	</currentcharges>
	<details>
		<rateschedule>
			<name/>
		</rateschedule>
		<distribution>
			<charges>
				<charge>
					<description/>
					<total/>
				</charge>
			</charges>
			<total/>
		</distribution>
		<service>
			<charges>
				<charge>
					<description/>
					<total/>
				</charge>
			</charges>
			<total/>
		</service>
		<tax>
			<charges>
				<charge>
					<description/>
					<total/>
				</charge>
			</charges>
			<total/>
		</tax>
		<total/>
	</details>
	<billableusage>
		<rateschedule>
			<name/>
		</rateschedule>
	</billableusage>
	<measuredusage>
		<meter type="">
			<estimated/>
			<identifier>027870434</identifier>
			<register>
				<identifier/>
				<description/>
				<total/>
			</register>
		</meter>
		<meter type="">
			<estimated/>
			<identifier>028702956</identifier>
			<register>
				<identifier/>
				<description/>
				<total/>
			</register>
		</meter>
		<meter type="">
			<estimated/>
			<identifier>084010385</identifier>
			<register>
				<identifier/>
				<description/>
				<total/>
			</register>
		</meter>
		<nextreaddate>2009-11-04</nextreaddate>
	</measuredusage>
</utilitybill>
